;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	haml-electric-backspace
	))

(setq mc/cmds-to-run-once
      '(
	indent-for-tab-command
	kill-region
	markdown-exdent-or-delete
	yaml-electric-backspace
	))
